security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_ACHETEUR:  ROLE_ACHETEUR
        ROLE_VENDEUR: ROLE_VENDEUR
        ROLE_CHEF_EQUIPE: ROLE_CHEF_EQUIPE
        ROLE_REPARATEUR: ROLE_REPARATEUR

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login


            logout:       true
            anonymous:    true

    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }
            - { path: ^/acheteur/, role: ROLE_ACHETEUR }
            - { path: ^/vendeur/, role: ROLE_VENDEUR }
            - { path: ^/chef-equipe/, role:  ROLE_EQUIPE  }
            - { path: ^/reparateur/, role: ROLE_REPARATEUR }


