user_page_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

user_inscription:
    path:     /register
    defaults: { _controller: UserBundle:Default:inscription}
homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:Acces}
