<?php

namespace ProduitBundle\Repository;

/**
 * CommentaireProdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireProdRepository extends \Doctrine\ORM\EntityRepository
{

    public function fiii($x){
        $qry=$this->getEntityManager()
            ->createQuery("SELECT m FROM ProduitBundle:CommentaireProd m WHERE m.produit = :x")
            ->setParameter(':x',$x);
        return $qry->getResult();
    }
}
