<?php

namespace ProduitBundle\Repository;

/**
 * PrefereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrefereRepository extends \Doctrine\ORM\EntityRepository
{
}
