<?php

namespace ProduitBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function Search($word){


  $qry=$this->createQueryBuilder('m')
    ->where('m.nom LIKE :param')
    ->orwhere('m.modele LIKE :param')
    ->orwhere('m.prix LIKE :param')
    ->orwhere('m.type LIKE :param')
    ->orwhere('m.description LIKE :param')
    ->setParameter('param', '%'.$word.'%');
        return $qry->getQuery()->getResult();

    }
    public function findFF($titre){
        $qry=$this->getEntityManager()
            ->createQuery("SELECT COUNT (m) as qte FROM ProduitBundle:Produit m WHERE m.Categorie = :tit")
            ->setParameter(':tit',$titre);
        return $qry->getResult();
    }
}
