<?php

namespace ProduitBundle\Repository;

/**
 * RatingPrdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingPrdRepository extends \Doctrine\ORM\EntityRepository
{
}
